version: 1.0.{build}

version: 1.0.{build}

environment:
  matrix:
    !include .appveyor/msvc/matrix.yml
    # !include .appveyor/mingw/matrix.yml


build_script:
  - ps: |
      $compiler = $env:COMPILER
      $script = ".appveyor/$compiler/build.ps1"
      if (Test-Path $script) {
          & $script
      } else {
          Write-Host "No build script found for $compiler"
          exit 1
      }
