version: 1.0.{build}

# Include compiler-specific matrices
# Comment out any include to disable that compiler family
- include: .appveyor/msvc/matrix.yml
- include: .appveyor/mingw/matrix.yml

# Shared build dispatcher
build_script:
  - ps: |
      $compiler = $env:COMPILER
      $script = ".appveyor/$compiler/build.ps1"
      if (Test-Path $script) {
          & $script
      } else {
          Write-Host "No build script found for $compiler"
          exit 1
      }
