version: 1.0.{build}

# One job per compiler image
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      GENERATOR: "Visual Studio 17 2022"

build_script:
  - ps: |
      function Build-And-Test($Generator, $Arch, $Dir) {
          Write-Host "=== Building $Arch with $Generator ==="
          cmake -S . -B $Dir -G "$Generator" -A $Arch
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          cmake --build $Dir --config Release
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

          Write-Host "=== Running tests in $Dir ==="
          Push-Location $Dir
          ctest -C Release --output-on-failure --timeout 60
          $result = $LASTEXITCODE
          Pop-Location
          if ($result -ne 0) { exit $result }
      }

      # Call the function for each architecture
      Build-And-Test "$env:GENERATOR" Win32 build_x86
      Build-And-Test "$env:GENERATOR" x64   build_x64

      # Optional ARM/ARM64
      # Build-And-Test "$env:GENERATOR" ARM   build_arm
      # Build-And-Test "$env:GENERATOR" ARM64 build_arm64
