version: 1.0.{build}

# One job per compiler image
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      GENERATOR: "Visual Studio 17 2022"

build_script:
  - cmd: |
      echo === Building with %GENERATOR% ===

      rem --- x86 ---
      cmake -S . -B build_x86 -G "%GENERATOR%" -A Win32
      cmake --build build_x86 --config Release

      rem --- x64 ---
      cmake -S . -B build_x64 -G "%GENERATOR%" -A x64
      cmake --build build_x64 --config Release

    # rem --- ARM (skip if not supported) ---
    # cmake -S . -B build_arm -G "%GENERATOR%" -A ARM || echo "ARM not supported on this image"
    # cmake -S . -B build_arm -G "%GENERATOR%" -A ARM && cmake --build build_arm --config Release || echo "ARM build skipped"

    # rem --- ARM64 (skip if not supported) ---
    # cmake -S . -B build_arm64 -G "%GENERATOR%" -A ARM64 || echo "ARM64 not supported on this image"
    # cmake -S . -B build_arm64 -G "%GENERATOR%" -A ARM64 && cmake --build build_arm64 --config Release || echo "ARM64 build skipped"

test_script:
  - cmd: |
      cd build_x64
      ctest -C Release --output-on-failure
