  # WARNING: never change the indentation of the lines below - it matters for YAML parsing!
  - COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "MinGW Makefiles"
    MINGW_PATH: "C:\\MinGW\\bin"

  - COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "MinGW Makefiles"
    MINGW_PATH: "C:\\mingw-w64\\i686-7.3.0-posix-dwarf-rt_v5-rev0\\mingw32\\bin"

  - COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "MinGW Makefiles"
    MINGW_PATH: "C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\\mingw64\\bin"

  - COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "MinGW Makefiles"
    MINGW_PATH: "C:\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin"

  - COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: "MinGW Makefiles"
    MINGW_PATH: "C:\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
