# AppVeyor Matrix Merger
# 
# This script is automatically executed by Git hooks during pre-commit.
# It merges all matrix.yml files from subdirectories into a unified appveyor.yml.
# 
# DO NOT MODIFY THE GENERATED appveyor.yml MANUALLY - changes will be overwritten!

$ErrorActionPreference = "Stop"

# Get the directory containing this script (.appveyor)
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# Output file path (appveyor.yml in repository root)
$outputFile = Join-Path $root "..\appveyor.merged.yml"

Write-Host "Merging AppVeyor matrix fragments..."

# Collect all matrix entries from subdirectories
$matrixContent = @()
$totalFiles = 0

Get-ChildItem $root -Directory | ForEach-Object {
    $matrixFile = Join-Path $_.FullName "matrix.yml"
    if (Test-Path $matrixFile) {
        Write-Host "  Processing $($_.Name)/matrix.yml"
        $matrixContent += Get-Content $matrixFile
        $totalFiles++
    }
}

if ($matrixContent.Count -eq 0) {
    Write-Error "No matrix.yml files found in subdirectories!"
    exit 1
}

# Generate the final AppVeyor configuration
$header = @"
# This file is automatically generated by .appveyor/merge_matrices.ps1
# which is executed by Git pre-commit hooks (See .appveyor/hooks).
#
# DO NOT EDIT THIS FILE MANUALLY - your changes will be lost!
# To modify the build matrix, edit the matrix.yml files in .appveyor/ subdirectories.

version: 1.0.{build}

environment:
  matrix:
"@

$buildScript = @"

build_script:
  - ps: |
      # Invoke the build dispatcher with environment parameters
      & ".appveyor/dispatch_build.ps1" -Compiler `$env:COMPILER -Generator `$env:GENERATOR
"@

$finalConfig = $header + "`n" + ($matrixContent -join "`n") + $buildScript

# Write the merged configuration
Set-Content $outputFile -Value $finalConfig -Encoding UTF8
Write-Host "Successfully merged $totalFiles matrix files into appveyor.merged.yml"
