#pragma once

#ifndef PM_COMPILER_VERSION_MAJOR
#define PM_COMPILER_VERSION_MAJOR (_MSC_VER / 100)
#endif

#ifndef PM_COMPILER_VERSION_MINOR
#define PM_COMPILER_VERSION_MINOR (_MSC_VER % 100)
#endif

#ifdef _MSC_FULL_VER
#ifndef PM_COMPILER_VERSION_BUILD
#define PM_COMPILER_VERSION_BUILD ((_MSC_FULL_VER / 10000) % 10000)
#endif

#ifndef PM_COMPILER_VERSION_REVISION
#define PM_COMPILER_VERSION_REVISION (_MSC_FULL_VER % 10000)
#endif
#else
#ifndef PM_COMPILER_VERSION_BUILD
#define PM_COMPILER_VERSION_BUILD 0
#endif

#ifndef PM_COMPILER_VERSION_REVISION
#define PM_COMPILER_VERSION_REVISION 0
#endif
#endif

#ifndef PM_COMPILER_NAME
#define PM_COMPILER_NAME "MSVC"
#endif

#ifndef PM_CC_MSVC
#define PM_CC_MSVC \
    ((PM_COMPILER_VERSION_MAJOR * 10000) + (PM_COMPILER_VERSION_MINOR * 100) + PM_COMPILER_VERSION_BUILD)
#endif