#pragma once

#ifndef PM_COMPILER_VERSION_MAJOR
#define PM_COMPILER_VERSION_MAJOR __GNUC__
#endif

#ifndef PM_COMPILER_VERSION_MINOR
#define PM_COMPILER_VERSION_MINOR __GNUC_MINOR__
#endif

#ifndef PM_COMPILER_VERSION_BUILD
#define PM_COMPILER_VERSION_BUILD __GNUC_PATCHLEVEL__
#endif

#ifndef PM_COMPILER_VERSION_REVISION
#define PM_COMPILER_VERSION_REVISION 0
#endif

#ifndef PM_COMPILER_NAME
#define PM_COMPILER_NAME "GCC"
#endif

#ifndef PM_CC_GCC
#define PM_CC_GCC \
    ((PM_COMPILER_VERSION_MAJOR * 10000) + (PM_COMPILER_VERSION_MINOR * 100) + PM_COMPILER_VERSION_BUILD)
#endif