#pragma once
#include <crtversion.h>

#ifndef STDC_CRT_VERSION_MAJOR
#    define STDC_CRT_VERSION_MAJOR _VC_CRT_MAJOR_VERSION
#endif

#ifndef STDC_CRT_VERSION_MINOR
#    define STDC_CRT_VERSION_MINOR _VC_CRT_MINOR_VERSION
#endif

#ifndef STDC_CRT_VERSION_BUILD
#    define STDC_CRT_VERSION_BUILD _VC_CRT_BUILD_VERSION
#endif

#ifndef STDC_CRT_VERSION_REVISION
#    define STDC_CRT_VERSION_REVISION _VC_CRT_RBUILD_VERSION
#endif

#ifndef STDC_CRT_NAME
#    define STDC_CRT_NAME "MSVC Universal CRT"
#endif

#ifndef STDC_CRT_MSUCRT
#    define STDC_CRT_MSUCRT ((STDC_CRT_VERSION_MAJOR * 1000000) + (STDC_CRT_VERSION_MINOR * 10000) + (STDC_CRT_VERSION_BUILD * 100) + STDC_CRT_VERSION_REVISION)
#endif
