#pragma once
#include <crtversion.h>

#define PM_CRT_VERSION_MAJOR _VC_CRT_MAJOR_VERSION
#define PM_CRT_VERSION_MINOR _VC_CRT_MINOR_VERSION
#define PM_CRT_VERSION_BUILD _VC_CRT_BUILD_VERSION
#define PM_CRT_VERSION_REVISION _VC_CRT_RBUILD_VERSION
#define PM_CRT_NAME "MSVC Universal CRT"
